blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/afadesigns/zshellcheck/discussions/new?category=q-a
    about: Ask the community for help with using ZShellCheck.
  - name: Share an Idea
    url: https://github.com/afadesigns/zshellcheck/discussions/new?category=ideas
    about: Share ideas for new features or Katas before opening a formal request.
